name: dyson
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=22.0.4
  - wordcloud=1.6.0
  - jupyter_contrib_nbextensions
  - pip:
      - pandas==1.4.1
      - numpy==1.22.0
      - nb-black==1.0.7
      - seaborn==0.11.2
      - plotly==5.6.0
      - pandas_profiling==3.1.0
      - scikit-learn==1.0.2
      - ipywidgets==7.7.0
